### ISSUE TITLE
Consider adding Backpack to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [Riku32/Baka.js#13]
Hey @JSH32, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by kakarot-dev** [comment]
this is still in early stages 😄 
I  think riku will add it after v1 is released

**Comment by JSH32** [comment]
> this is still in early stages 😄 I think riku will add it after v1 is released

We can just add it now, already on it.

**Comment by JSH32** [comment]
Made PR: https://github.com/SeaQL/sea-orm/pull/567

**Comment by kakarot-dev** [comment]
Oki doki

**Comment by billy1624** [comment]
Thanks!! @JSH32 @kakarot-dev 
Keep up with the great work! :)
