### ISSUE TITLE
Image embedding on whatsapp

### ISSUE THREAD

**Issue by kakarot-dev** [Riku32/Baka.js#17]
As much as i hate to say it, whatsapp is used too much ( my opinion )

Well anyway, i would like cdn to embed there too!!

**Comment by JSH32** [comment]
I'm confused as to what this means. Images are images and if you use S3 it will embed because of multipart. If you send as a normal link being served through the API it will still embed regardless. Mind elaborating?

**Comment by kakarot-dev** [comment]
Basically while sharing the cdn link, we mostly believe the image to embed in chat applications like discord
But whatsapp doesnt embed, so is there a way to make whatsapp show the pic?

**Comment by JSH32** [comment]
This seems like more of a host problem than a software problem, I'll read up on S3 docs to see of this is part of ACL or something but chances are, your host is weird.

**Comment by JSH32** [comment]
Closing since this is dependent on the specific S3 provider used.
