### ISSUE TITLE
Add kubernetes support

### ISSUE THREAD

**Issue by JSH32** [Riku32/Baka.js#20]
Allow running the API, distributed in kubernetes. Why? It's cool

### Requirements
- *Only* run api, front-end seperate
- Run migrations in a helm chart to prevent concurrent migration runs
- Dissalow local storage in kube (some people might be using rclone so don't actually do this)
- Documentation on how to run (and how it works)

**Comment by mterlyn** [comment]
I'd like to assist in adding K8s support, any idea on where to start?

**Comment by JSH32** [comment]
> I'd like to assist in adding K8s support, any idea on where to start?

First we should probably finish the project hence the fact that this issue is on backlog. The real issue I'm facing is migrations running only once per deployment. The stack and env file will likely be very different from the docker-compose setup we have right now which needs to be documented on the wiki. I'll let you know when work starts on this again.

Also a discussion topic: Some people use kubernetes to run just one node of everything. We can't build one way of deployment for all use cases when the community uses it differently. How should we approach this?

**Comment by JSH32** [comment]
Closing because docker containers are all we need for Kubernetes support. To make it configurable we shouldn't require a specific configuration. Maybe we can make a guide on the Wiki once V1 is nearing release but right now this is pointless.
